### PR TITLE
refactor: untabify and use k&r c-style (tab:8)

### PR DESCRIPTION
**Pull request by nsulmol**
here, we do 2 things:
- run untabify to remove mistakenly added tabs.
- re-indent everything with k&r c-style, with c-basic-offset set to 8.

These are aiming to return this file to the gxsm3 coding standard.

### CODE REVIEW

**Comment by pyzahl** [comment]
let me know when you have completed you edits. Do not go too crazy on the style... but I appreciate.  Or is this "final"?

**Comment by nsulmol** [comment]
This is final for just spacing fixes. I figured it was worth running 'untabify' and 'indent-region', as they will auto-fix based on your style. No worries if you'd rather not merge!

**Comment by pyzahl** [comment]
What about you merge it and have easy future access as well -- I added you as collaborator to the Gxsm3 repo.

**Comment by nsulmol** [comment]
Hi Percy,

Do you mean merging this pull request, or both? If I can, I would be OK merging this request in (since it is just tabs/spacing changes), but would be more comfortable for a second pair of eyes reviewing my follow-up changelist (with the actual code changes).

I should note, however, that I do not appear to be a collaborator on the gxsm3 repo - perhaps the setting change did not go through?

Let me know how you would prefer to move forward, and I'll help how I can.

Thanks,
Nick

**Review by nsulmol — COMMENTED** [review]
Following Percy's feedback, I accept these changes. They only modify spacing, so should not affect the code in any way.

**Comment by nsulmol** [comment]
Pull request was closed, as I merged directly into gxsm3 (as per Percy's request).

**Pull request closed without merging**
